MODEL:
  KEYPOINT_ON: False
  LOAD_PROPOSALS: False
  META_ARCHITECTURE: "Segmentor"
  BACKBONE:
    NAME: "build_dino"
  DINO:
    SIZE: "small"
    LAYERS: [8,9,10,11]
    RESHAPE: True
    RESIZE: 256
    CROP_SIZE: 224
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255

SOLVER:
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002
  MAX_ITER: 1200000
  WARMUP_FACTOR: 1e-6
  WARMUP_ITERS: 1500
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  BACKBONE_MULTIPLIER: 0.1
  TEST_IMS_PER_BATCH: 1
  REFERENCE_WORLD_SIZE: 1
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: null
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: "ADAMW"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

DATASETS:
  TRAIN: ("ade20k_sem_seg_val",)
  TEST: ("ade20k_sem_seg_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

OUTPUT_DIR: ./output

TEST:
  EVAL_PERIOD: False
  MIN_SIZES: [256, 384, 512, 640, 768, 896]
  MAX_SIZE: 3584
  FLIP: True
  PRECISE_BN:
    ENABLED: False
    
INPUT:
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 2048
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512,512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 512
  FORMAT: "RGB"


VERSION: 2